services:
  - type: web
    name: telegram-bot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: APP_ENV
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: TELEGRAM_BOT_TOKEN
        sync: false  # Set in Render dashboard
      - key: OPENAI_API_KEY
        sync: false  # Set in Render dashboard
      - key: DATABASE_URL
        fromDatabase:
          name: telegram-bot-db
          property: connectionString

databases:
  - name: telegram-bot-db
    databaseName: telegram_bot
    user: telegram_bot_user
    plan: free
